version: '3.5'

services:
  zoo1:
    image: wurstmeister/zookeeper
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888

  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1
    ports:
      - "9092:9092"
    expose:
      - "9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9091,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9091,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      #KAFKA_DEFAULT_REPLICATION_FACTOR: ${REPLICATION_FACTOR}
      #KAFKA_NUM_PARTITIONS: ${NUM_PARTITIONS}
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka/kafka-logs-1
      KAFKA_AUTO_OFFSET_RESET: latest
      TOPIC_AUTO_CREATE: "true"
    depends_on:
      - zoo1
    volumes:
      - "./kafka-logs-1:/kafka/kafka-logs-1"

  kafka2:
    image: wurstmeister/kafka
    hostname: kafka2
    ports:
      - "9093:9093"
    expose:
      - "9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9091,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9091,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_DEFAULT_REPLICATION_FACTOR: ${REPLICATION_FACTOR}
#      KAFKA_NUM_PARTITIONS: ${NUM_PARTITIONS}
      KAFKA_BROKER_ID: 2
      KAFKA_LOG_DIRS: /kafka/kafka-logs-2
      KAFKA_AUTO_OFFSET_RESET: latest
      TOPIC_AUTO_CREATE: "true"
    depends_on:
      - zoo1
    volumes:
      - "./kafka-logs-2:/kafka/kafka-logs-2"

  kafka3:
    image: wurstmeister/kafka
    hostname: kafka3
    ports:
      - "9094:9094"
    expose:
      - "9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9091,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9091,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_DEFAULT_REPLICATION_FACTOR: ${REPLICATION_FACTOR}
#      KAFKA_NUM_PARTITIONS: ${NUM_PARTITIONS}
      KAFKA_BROKER_ID: 3
      KAFKA_LOG_DIRS: /kafka/kafka-logs-3
      KAFKA_AUTO_OFFSET_RESET: latest
      TOPIC_AUTO_CREATE: "true"
    depends_on:
      - zoo1
    volumes:
      - "./kafka-logs-3:/kafka/kafka-logs-3"

  app:
    links:
      - "kafka1:kafka1"
      - "kafka2:kafka2"
      - "kafka3:kafka3"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: on-failure
    build: .
    image: felian/try-kafka
    volumes:
      - "./config.yaml:/app/config.yaml"
